# Generated by Django 4.2.4 on 2023-08-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plan_Name', models.CharField(max_length=50)),
                ('Basic', models.IntegerField()),
                ('Standard', models.IntegerField()),
                ('Premium', models.IntegerField()),
            ],
        ),
    ]
