# Generated by Django 4.2.4 on 2023-08-06 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deep', '0004_current_plan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='current_plan',
        ),
    ]
